version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable  # Ganti dengan image yang sesuai, misalnya image Node.js

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:bDd/t9/35EkLrMEID6yvQYuwJc+/NIkxPfm+rtxdihA"
      - run:
          name: Install Dependencies
          command: |
            ssh -o StrictHostKeyChecking=no root@5.231.70.225 "source ~/.nvm/nvm.sh; cd ~/apps/my-resume; git pull; npm install"
      - run:
          name: Build Nuxt.js
          command: |
            ssh -o StrictHostKeyChecking=no root@5.231.70.225 "source ~/.nvm/nvm.sh; cd ~/apps/my-resume; rm -rf .nuxt .output; git pull; npm run build"
      - run:
          name: Build Docker Image
          command: |
            ssh -o StrictHostKeyChecking=no root@5.231.70.225 "cd ~/apps/my-resume; docker build -t rizzra/my-resume ."
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            ssh -o StrictHostKeyChecking=no root@5.231.70.225 "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin; docker push rizzra/my-resume"

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:bDd/t9/35EkLrMEID6yvQYuwJc+/NIkxPfm+rtxdihA"
      - run:
          name: Deploy to VPS using Portainer
          command: |
            ssh -o StrictHostKeyChecking=no root@5.231.70.225 "docker pull rizzra/my-resume; docker stop my-resume || true; docker rm my-resume || true; docker run -d -p 3000:3000 --name my-resume rizzra/my-resume"  

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

