version: 2.1

executors:
  docker-executor:
    docker:
<<<<<<< HEAD
      - image: circleci/node:16  # Ganti dengan image yang sesuai, misalnya image Node.js
<<<<<<< HEAD
        resource_class: rizzra26/vpsku
=======
        environment:
          DOCKER_TLS_CERTDIR: "/certs"
=======
      - image: circleci/python:3.8  # Ganti dengan image yang sesuai, misalnya image Node.js
>>>>>>> parent of 9fee00e (Fix: change circleci image to node:16)
>>>>>>> parent of 65d1a66 (Fix: conflicts)
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Check Docker Daemon
          command: |
            docker info
      - run:
          name: Build Nuxt.js
          command: |
            npm run build
      - run:
          name: Build Docker Image
          command: |
            docker build -t rizzra/my-resume .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push rizzra/my-resume

  deploy:
    docker:
      - image: circleci/python:3.8  # Ganti dengan image yang sesuai
    steps:
      - checkout
      - run:
          name: Deploy to VPS using Portainer
          command: |
            curl -fsSL https://raw.githubusercontent.com/portainer/portainer-ce/master/scripts/portainer.sh | sh  # Install Portainer di VPS jika belum ada
            docker pull rizzra/my-resume  # Tarik Docker image yang telah dipush ke Docker Hub
            docker stop my-resume || true  # Stop container sebelumnya
            docker rm my-resume || true    # Hapus container sebelumnya
            docker run -d -p 80:3000 --name my-resume rizzra/my-resume  # Jalankan aplikasi Nuxt.js di VPS

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

