version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:current  # Ganti dengan image yang sesuai, misalnya image Node.js
    resource_class: rizzra26/my-resume

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Build Nuxt.js
          command: |
            npm run build
      - run:
          name: Build Docker Image
          command: |
            docker build -t rizzra/my-resume .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push rizzra/my-resume

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Deploy to VPS using Portainer
          command: |
            docker pull rizzra/my-resume  # Tarik Docker image yang telah dipush ke Docker Hub
            docker stop my-resume || true  # Stop container sebelumnya
            docker rm my-resume || true    # Hapus container sebelumnya
            docker run -d -p 80:3000 --name my-resume rizzra/my-resume  # Jalankan aplikasi Nuxt.js di VPS

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

