version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10  # Docker image untuk Node.js
    steps:
      - checkout  # Menarik kode dari repositori
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build Nuxt app
          command: |
            npm run build
      - run:
          name: Build Docker image
          command: |
            docker build -t my-resume .

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker tag my-resume $DOCKER_USERNAME/my-resume:latest
            docker push $DOCKER_USERNAME/my-resume:latest
      - run:
          name: Deploy to VPS
          command: |
            ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "docker pull $DOCKER_USERNAME/my-resume:latest; docker-compose -f ~/apps/my-resume/docker-compose.yml up -d"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
